### ISSUE TITLE
Error 500 at /search?q=underscore

### ISSUE THREAD

**Issue by eavae** [npm/npm-www#969]
Stack:
```
Error: connect ECONNREFUSED
    at ServerResponse.error (/home/work/edp-www/node_modules/error-page/error-page.js:108:20)
    at MC.ondone (/home/work/edp-www/routes/search.js:50:11)
    at MC.next (/home/work/edp-www/node_modules/emcee/emcee.js:45:12)
    at Request._callback (/home/work/edp-www/models/search.js:43:14)
    at self.callback (/home/work/edp-www/node_modules/request/index.js:148:22)
    at Request.EventEmitter.emit (events.js:95:17)
    at ClientRequest.self.clientErrorHandler (/home/work/edp-www/node_modules/request/index.js:257:10)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
```

Headers:
```
{
  "host": "edp.baidu.com",
  "x-real-ip": "172.20.130.142",
  "x-forwarded-for": "172.20.130.142",
  "connection": "close",
  "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36",
  "referer": "http://edp.baidu.com/search?q=jquery",
  "accept-encoding": "gzip, deflate, sdch",
  "accept-language": "zh-CN,zh;q=0.8,ja;q=0.6,en;q=0.4,zh-TW;q=0.2,nl;q=0.2",
  "ra-ver": "2.9.0",
  "ra-sid": "DCB52677-20150316-125600-0bac5f-16137b"
}
```

Error:
```
{
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
  "syscall": "connect"
}
```

Message:
```
connect ECONNREFUSED
```

Stamp: pid=23528 worker=2 274aa5bc4cd022d171e75f2b0e496a25710bf7e3 http://cq02-vs-fe00.cq02.baidu.com:10002

**Comment by zeke** [comment]
This repo is defunct. Please search for and/or reopen your issue here: https://github.com/npm/newww/issues/ -- thanks!
